# Generated by Django 3.1.2 on 2021-01-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210116_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
