# Generated by Django 3.1.2 on 2021-01-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210117_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_b',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_g',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_r',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
